export const DUMMY_EVENTS = [
  {
    id: "n1",
    image: "../img/event.png",
    date: "February 6th 2023",
    time: "10 PM to 12 PM",
    title: "Meet up Freelancer",
    discription: "Become a potential and professional freelancer",
  },
  {
    id: "n2",
    image: "../img/event.png",
    date: "February 6th 2023",
    time: "10 PM to 12 PM",
    title: "Meet up Freelancer",
    discription: "Become a potential and professional freelancer",
  },
  {
    id: "n3",
    image: "../img/event.png",
    date: "February 6th 2023",
    time: "10 PM to 12 PM",
    title: "Meet up Freelancer",
    discription: "Become a potential and professional freelancer",
  },
  {
    id: "n4",
    image: "../img/event.png",
    date: "February 6th 2023",
    time: "10 PM to 12 PM",
    title: "Meet up Freelancer",
    discription: "Become a potential and professional freelancer",
  },
  {
    id: "n5",
    image: "../img/event.png",
    date: "February 6th 2023",
    time: "10 PM to 12 PM",
    title: "Meet up Freelancer",
    discription: "Become a potential and professional freelancer",
  },
  {
    id: "n6",
    image: "../img/event.png",
    date: "February 6th 2023",
    time: "10 PM to 12 PM",
    title: "Meet up Freelancer",
    discription: "Become a potential and professional freelancer",
  },
];
